#! /bin/bash

if [[ $(uname -m) == 'arm64' ]]; then
  # use homebrew's ruby, since the default has bad packages
  export PATH="/opt/homebrew/lib/ruby/gems/3.3.0/bin:$PATH"
fi

bundle install --path vendor/bundle

open http://localhost:4000

bundle exec jekyll serve --host "0.0.0.0"
