#! /bin/bash

if [ ! -f _tailwind/tailwindcss ] ; then
  # or tailwindcss-macos-x64 for intel macs
  curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
  chmod +x tailwindcss-macos-arm64
  mv tailwindcss-macos-arm64 tailwindcss
fi

_tailwind/build

bundle install --path vendor/bundle

HOST=localhost
# HOST=Marvin.local

open http://$HOST:4000

bundle exec jekyll serve --host $HOST
